trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.9.4
      endpoint: github

variables:
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '019fa417-c816-4b0e-8487-259717145e7a'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      GithubAuthVariableGroup: rsg-bot
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNet21Version: "2.1.801"
      DotNetVersion: "2.2.401"
      DotNet3Version: "3.0.100-preview8-013656"
      NuGetVersion: "5.2.0"
